services:
  - type: web
    name: flask-playwright-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps
    startCommand: gunicorn 'app:create_app()'
    envVars:
      - key: FLASK_ENV
        value: production
